### ISSUE TITLE
Комментарии к проекту

### ISSUE THREAD

**Issue by lajulienn** [sevadp/8bit-tank-game-new-generation#1]
Отличный код! Буквально пара моментов есть. 

Хотелось бы все подобные числовые константы вынести из кода в конфиг:
![Screenshot from 2021-04-28 22-22-24](https://user-images.githubusercontent.com/17601470/116461143-94222000-a870-11eb-82c2-84021de219bd.png)

И названия файлов тоже:
![Screenshot from 2021-04-28 22-23-24](https://user-images.githubusercontent.com/17601470/116461148-95ebe380-a870-11eb-80c7-66ff36e29e8c.png)

Не поняла, для чего тут пустую строку прибавляем?
![Screenshot from 2021-04-28 22-24-46](https://user-images.githubusercontent.com/17601470/116461404-e2372380-a870-11eb-8bdc-ef1b1d11e80e.png)

**Comment by sevadp** [comment]
Всё исправил)
